repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      - id: ruff
      # - id: ruff-format

  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-bugbear==23.9.16
          - flake8-comprehensions==3.14.0
          - flake8-pytest-style==1.7.2
          - pep8-naming==0.13.3

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
